language: php
php:
  - '7.2'
install: composer update && sudo add-apt-repository -y ppa:ondrej/php &&
  sudo apt update && sudo apt install -y php7.2-curl && cp $TRAVIS_BUILD_DIR/.env.example $TRAVIS_BUILD_DIR/.env &&
  php $TRAVIS_BUILD_DIR/artisan key:generate
script:
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit $TRAVIS_BUILD_DIR/tests/
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit --coverage-clover=coverage.xml $TRAVIS_BUILD_DIR/tests/ --whitelist=$TRAVIS_BUILD_DIR/app/
after_success:
  - bash <(curl -s https://codecov.io/bash)